version: '3.3'

services:
  input:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    ports:
      - "8091:8091"
    container_name: input
    image: input

  json_serv:
    build:
      context: ./
      dockerfile: ./json_serv/Dockerfile
    ports:
      - "8092:8092"
    container_name: json_serv
    image: json_serv

  store:
    build:
      context: ./
      dockerfile: ./store/Dockerfile
    ports:
      - "8093:8093"
    container_name: store
    image: store
