# Generated by Django 4.0.6 on 2022-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('manipulation', models.IntegerField()),
                ('composure', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wits', models.IntegerField()),
                ('resolve', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Info',
            new_name='Roll',
        ),
    ]
