# Generated by Django 4.0.6 on 2022-07-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attributes_rename_info_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='charisma',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='composure',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='manipulation',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='resolve',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='stamina',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='wits',
            field=models.IntegerField(default=1),
        ),
    ]
