{
 "title": "MONITORING 2.0",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DISK USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node\", instance=\"localhost:9100\", mountpoint=\"/\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", instance=\"localhost:9100\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (rate(node_cpu_seconds_total{job=\"node\", instance=\"localhost:9100\", mode=\"user\"} [1m]))"
    },
    {}
   ]
  },
  {
   "title": "RAM USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", instance=\"localhost:9100\"} - node_memory_MemFree_bytes{job=\"node\", instance=\"localhost:9100\"} - node_memory_Cached_bytes{job=\"node\", instance=\"localhost:9100\"} - node_memory_Buffers_bytes{job=\"node\", instance=\"localhost:9100\"}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", instance=\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "I/O OPERATIONS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node\", instance=\"localhost:9100\", device=\"sda\"}[1m])"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node\", instance=\"localhost:9100\", device=\"sda\"}[1m])"
    }
   ]
  }
 ]
}